# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy remaining source
COPY . .

# Build the project
RUN npx tsc

# Expose port if necessary (but it's stdio so none required)

# Set environment variable if needed, but otherwise allow override
ENV WORKDAY_CLIENT_ID="your_client_id"
ENV WORKDAY_CLIENT_SECRET="your_client_secret"
ENV WORKDAY_TENANT="your_tenant"
ENV WORKDAY_REFRESH_TOKEN="your_refresh_token"
ENV WORKDAY_ACESSTOKEN="your_access_token"

# Start the MCP server
CMD [ "node", "build/index.js" ]